name: Lerna publish

on:
  push:
    branches: [ yarn-workspaces ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Install dependencies
        run: yarn policies set-version 3.2.1 && yarn && yarn plugin import workspace-tools && yarn plugin import version

      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: HUSKY_SKIP_HOOKS=1 yarn workspaces foreach npm publish --tolerate-republish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
